### PR TITLE
Adds Tilix color schemes

### PR DESCRIPTION
**Pull request by bl1nk**
Hey there! I have created all variants of Selenized for [Tilix](https://gnunn1.github.io/tilix-web/) using the colors listed in `the-values.md`. Happy to make changes if something is missing or wrong.

### CODE REVIEW

**Comment by jan-warchol** [comment]
Hello,

Awesome, thanks for sharing! Have you seen the code in [`utils`](https://github.com/jan-warchol/selenized/tree/master/utils#generating-config-files)? It contains a script for generating config files from template (example template: https://github.com/jan-warchol/selenized/blob/master/utils/templates/template-test.example.template), so that when I release a new version of selenized I can easily update all config files. Could you create such a template? Let me know if you have any questions.

thanks!

**Comment by bl1nk** [comment]
To be honest I did not see that, I'll add templates for both Tilix and Alacritty. :)

**Comment by bl1nk** [comment]
I have updated this PR and added a template for Tilix. The values changed a bit. This also fixes #37.

**Comment by jan-warchol** [comment]
Thanks! Looks good, but I'd like to double-check at my computer tomorrow. :)

czw., 25 kwi 2019, 23:16 użytkownik Markus Cisler <notifications@github.com>
napisał:

**Comment by jan-warchol** [comment]
As far as I can see everything looks right. Great, thanks a lot! <3

**Pull request merged**
