### PR TITLE
Vim: improve coloring of keyword completion (fix #33)

### LINKED ISSUE #33: Vim suggestions look bad
screenshot2

### PR DESCRIPTION
**Pull request by jan-warchol**
image

How do you like this, @dngray @Envielox ?

### CODE REVIEW

**Comment by dngray** [comment]
Looks good to me. I assume the last line being highlighted "return a replacement string to be used." is supposed to be like that?

**Comment by jan-warchol** [comment]
> I assume the last line being highlighted "return a replacement string to be used." is supposed to be like that?

Actually I'm not sure what is responsible for this particular element as it doesn't appear in my vim. I've pushed another commit, can you check whether it changed?

**Comment by dngray** [comment]
> Actually I'm not sure what is responsible for this particular element as it doesn't appear in my vim. I've pushed another commit, can you check whether it changed?

It didn't appear to change anything. It also seems now this doesn't work at all with nvimqt (even in broken form), these two commits I don't think are responsible. Hopefully that will get fixed when we solve https://github.com/jan-warchol/selenized/issues/47 and use colortheme.

**Comment by dngray** [comment]
I tested this with [lifepillar/vim-solarized8](https://github.com/lifepillar/vim-solarized8) (nvim-qt) and the bottom line doesn't appear to be highlighted.

**Comment by dngray** [comment]
Awesome this seems to be fixed:

**Pull request closed without merging**
